tor:
  proxy_host: 127.0.0.1
  proxy_port: 8118
  control_port: 9051
  control_password: null
  circuit_refresh_interval: 300
  max_circuit_failures: 5

scrapy:
  user_agent: 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53.0) Gecko/20100101 Firefox/53.0'
  download_delay: 3
  randomize_download_delay: 0.5
  concurrent_requests: 1
  retry_times: 3
  retry_http_codes: [500, 502, 503, 504, 408, 429]

selenium:
  render_timeout: 300

redis:
  host: 127.0.0.1
  port: 6379
  db: 0

data_storage:
  hash_algorithm: sha256

target_sites:
  #- name: "CL0P^_- LEAKS"
  #  url: "http://santat7kpllt6iyvqbr7q4amdv6dzrh6paatvyrzl7ry3zm72zigf4ad.onion/"
  #  category: "data_leak_site"
  #  use_selenium: true
  #  rules:
  #    follow_links: ".g-main-nav .g-dropdown a.g-menu-item-container"
  #    pagination: null
  #    post_title: "h2.g-title"
  #    post_author: null
  #    post_content: "div.platform-content"
  #    images: ".platform-content img::attr(src )"

  # - name: "Dread Forum"
  #   url: "http://dreadytofatroptsdj6io7l3xptbet6onoyno2yv7jicoxknyazubrad.onion/"
  #   category: "forum"
  #   use_selenium: true
  #   rules:      
  #     follow_links: ".postBoard .item a.title"
  #     pagination: ".pagination a.next"
  #     post_title: "h1.p-title-value"
  #     post_author: ".message-userDetails .username"
  #     post_content: ".message-content .bbWrapper"

  - name: "Best Carding World"
    url: "http://bestteermb42clir6ux7xm76d4jjodh3fpahjqgbddbmfrgp4skg2wqd.onion/"
    category: "marketplace"
    use_selenium: false 
    rules:
      follow_links: "a.forumtitle, a.topictitle"
      post_container: "div.post"
      pagination: ".pagination .next a"
      post_author: ".author"
      post_content: ".content"

  - name: "BFD Forum"
    url: "http://bfdxjkv5e2z3ilrifzbnvxxvhbzsj67akjpj3zc6smzr4vv6oz565gyd.onion/"
    category: "forum"
    use_selenium: false
    rules:
      follow_links: ".node-title a, .structItem-title a"
      post_container: "article.message"
      pagination: ".pageNav-jump--next"
      post_author: ".message-name"
      post_content: ".message-body"